### PR TITLE
Improvement/51 improve reservation details design

### LINKED ISSUE #51: Improve Reservation Details design

### LINKED ISSUE #57: Improve Book Details design

### PR DESCRIPTION
**Pull request by laureansvictor**
Changed book details and book reservation details appearance to be closer to the mockup ones.

Book reservation detail: 
Screenshot from 2022-05-31 11-48-43

Book detail:
Screenshot from 2022-05-31 11-51-10

### CODE REVIEW

**Comment by ruialves35** [comment]
I would just give a bit more bottom padding at the text "Nenhuma unidade disponivel", put the book image down a bit, and change the text "Devolução: data1 - data2" to "Devolver em: " and make the account of data2 - data1 to appear "14 dias" or "1 mes e 14 dias", something like that

**Comment by laureansvictor** [comment]
> I would just give a bit more bottom padding at the text "Nenhuma unidade disponivel", put the book image down a bit, and change the text "Devolução: data1 - data2" to "Devolver em: " and make the account of data2 - data1 to appear "14 dias" or "1 mes e 14 dias", something like that

@ruialves35  the logic from the devolution is coming from the function getReturnDate() in the book reservation. And whenever the reservation is fulfilled  it will say when to get in the same way you are suggesting.. as you can see the reservation is yet to start.

What i can do is either put another message like "Reserva não iniciada" ou simplesmente por um " - " significando que a reserva está pendente de começo (visto que ainda vou reservar daqui alguns dias".
Screenshot from 2022-05-31 11-47-02

**Comment by ruialves35** [comment]
> > I would just give a bit more bottom padding at the text "Nenhuma unidade disponivel", put the book image down a bit, and change the text "Devolução: data1 - data2" to "Devolver em: " and make the account of data2 - data1 to appear "14 dias" or "1 mes e 14 dias", something like that
> 
> @ruialves35 the logic from the devolution is coming from the function getReturnDate() in the book reservation. And whenever the reservation is fulfilled it will say when to get in the same way you are suggesting.. as you can see the reservation is yet to start.
> 
> What i can do is either put another message like "Reserva não iniciada" ou simplesmente por um " - " significando que a reserva está pendente de começo (visto que ainda vou reservar daqui alguns dias". Screenshot from 2022-05-31 11-47-02

Ah I see. We have to discuss that. I didn't remember about that case, I was just thinking about when the user already had the book and had to return it

**Comment by BrunoRosendo** [comment]
I think it looks pretty good!
However, we need to use the placeholder image here as well (same as in the book container). I also think it'd be nice to have "Português" instead of por and so on, if possible.
Asides from that, sometimes I get an overflow. Maybe making the page a scrollView would fix it?
image

**Comment by laureansvictor** [comment]
> I think it looks pretty good! However, we need to use the placeholder image here as well (same as in the book container). I also think it'd be nice to have "Português" instead of por and so on, if possible. Asides from that, sometimes I get an overflow. Maybe making the page a scrollView would fix it? image

I don't know why we aren't using the right image there, but I've managed to fix it.
In regards to the 'por', 'eng' and etc is coming from the book creation, when the scrapper grabs the information and build the book object the field language of this book contains this string and this is all we use.

Screenshot from 2022-06-05 14-03-27

**Comment by ruialves35** [comment]
> > I think it looks pretty good! However, we need to use the placeholder image here as well (same as in the book container). I also think it'd be nice to have "Português" instead of por and so on, if possible. Asides from that, sometimes I get an overflow. Maybe making the page a scrollView would fix it? image
> 
> I don't know why we aren't using the right image there, but I've managed to fix it. In regards to the 'por', 'eng' and etc is coming from the book creation, when the scrapper grabs the information and build the book object the field language of this book contains this string and this is all we use.
> 
> Screenshot from 2022-06-05 14-03-27

Instead of putting ${this.book.language} we could just use a map to get "por" from the catalog output. But I don't know if we have time to that, so I guess we can just close this after one last review

**Review by BrunoRosendo — APPROVED** [review]

**Pull request merged**
